INSERT INTO USER (BIRTH_DATE , GENDER, NAME ) VALUES (TO_DATE('26/05/1998', 'DD/MM/YYYY'), 'Feminino', 'Laryssa');
INSERT INTO USER (BIRTH_DATE , GENDER, NAME ) VALUES (TO_DATE('05/08/2000', 'DD/MM/YYYY'), 'Masculino', 'Guilherme');
INSERT INTO USER (BIRTH_DATE , GENDER, NAME ) VALUES (TO_DATE('15/03/1997', 'DD/MM/YYYY'), 'Feminino', 'Taynara');
INSERT INTO USER (BIRTH_DATE , GENDER, NAME ) VALUES (TO_DATE('16/10/1996', 'DD/MM/YYYY'), 'Masculino', 'William');